version: "3.9"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
    environment:
      - SPRING_PROFILE=docker

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: express_cleaning
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
