default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  DATABASE_URL: <%= ENV['DATABASE_URL'].gsub('?', '_development?') %>
test:
  <<: *default
  DATABASE_URL: <%= ENV['DATABASE_URL'].gsub('?', '_test?') %>

production:
  <<: *default
  DATABASE_URL: <%= ENV['DATABASE_URL'].gsub('?', '_production?') %>