CREATE TABLE `service` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `backyard_hours` int NOT NULL,
  `backyard_value` decimal(38,2) NOT NULL,
  `bathroom_hours` int NOT NULL,
  `bathroom_value` decimal(38,2) NOT NULL,
  `bedroom_hours` int NOT NULL,
  `bedroom_value` decimal(38,2) NOT NULL,
  `percentage_commission` int NOT NULL,
  `kitchen_hours` int NOT NULL,
  `kitchen_value` decimal(38,2) NOT NULL,
  `living_room_hours` int NOT NULL,
  `living_room_value` decimal(38,2) NOT NULL,
  `min_value` decimal(38,2) NOT NULL,
  `name` varchar(50) NOT NULL,
  `others_hours` int NOT NULL,
  `others_value` decimal(38,2) NOT NULL,
  `position` int NOT NULL,
  `qtd_hours` int NOT NULL,
  `num_hours` int NOT NULL,
  PRIMARY KEY (`id`)
)