CREATE SEQUENCE daily_seq;

CREATE TABLE IF NOT EXISTS daily (
  id bigint NOT NULL DEFAULT NEXTVAL ('daily_seq'),
  created_at timestamp(6) NOT NULL,
  updated_at timestamp(6) NOT NULL,
  neighborhood varchar(30) NOT NULL,
  cep varchar(8) NOT NULL,
  city varchar(30) NOT NULL,
  ibge_code varchar(255) NOT NULL,
  complement varchar(100) DEFAULT NULL,
  attendance_date timestamp(6) NOT NULL,
  state varchar(2) NOT NULL,
  street varchar(60) NOT NULL,
  cancellation_reason varchar(255) DEFAULT NULL,
  number varchar(10) NOT NULL,
  observations varchar(255) DEFAULT NULL,
  bathroom_num int NOT NULL,
  kitchen_num int NOT NULL,
  other_num int NOT NULL,
  backyard_num int NOT NULL,
  bedroom_num int NOT NULL,
  living_room_num int NOT NULL,
  status varchar(255) NOT NULL DEFAULT 'NO_PAYMENT',
  attendance_time int NOT NULL,
  commission_value decimal(19,2) NOT NULL,
  price decimal(19,2) NOT NULL,
  client_id bigint NOT NULL,
  cleaner_id bigint DEFAULT NULL,
  service_id bigint NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (service_id) REFERENCES service (id),
  FOREIGN KEY (cleaner_id) REFERENCES user (id),
  FOREIGN KEY (client_id) REFERENCES user (id)
);
